### ISSUE TITLE
Interaction plot: change color of nodes not present in the module

### ISSUE THREAD

**Issue by matheuscburger** [csbl-usp/CEMiTool#19]
Talking with Helder and @thiagodch  we came to the conclusion that it would be interesting to color differently the genes that are in the network but are not part of the module generated by CEMiTool.
I will not have time to make these modifications.

I think these are the necessary steps to get the job done:
1) Add an attribute to the vertices with the information of genes in module (cem@interactions)
2) Include this column as color [here](https://github.com/csbl-usp/CEMiTool/blob/83b29ab40fc8ecde1b213cdb20d2693432fd3f3c/R/visualization.R#L349)

**Comment by pedrostrusso** [comment]
So currently we show this information only for the module hubs (via the labels in the interaction network). What you're suggesting is that we instead color all nodes according to their "origin"? 
If I understand correctly, then we'll have 3 colors for the nodes in a module (if it came from co-expression, coexpression+interaction and interaction). Then I would suggest for us to get rid of the modules' unique colors, because it might get quite confusing (for example, the coexpression nodes in M1 would be blue, with the coexpression+interaction green and the interaction red, but for M2 the coexpression nodes would be yellow, while the other colors are the same as from M1)
