### ISSUE TITLE
Replacing previous import "X" by "Y" when loading 'CEMiTool' 

### ISSUE THREAD

**Issue by pedrostrusso** [csbl-usp/CEMiTool#21]
In the ggnetwork_fix branch I attempted to recreate the ggnetwork output for the interaction graphs using ggplot2 and ggrepel and it worked. However, now we have a few more warning messages about functions sharing the same names. Does anyone have any suggestions about how to address these problems?

```
Warning: replacing previous import ‘pracma::cutpoints’ by ‘sna::cutpoints’ when loading ‘CEMiTool’
Warning: replacing previous import ‘WGCNA::cor’ by ‘stats::cor’ when loading ‘CEMiTool’
Warning: replacing previous import ‘sna::degree’ by ‘igraph::degree’ when loading ‘CEMiTool’
```

**Comment by pedrostrusso** [comment]
About the last one, I'm trying to see if I can substitute the `igraph` package for the `network` package (as I'm using the latter to make the network objects in the interactions graphs), but I'm starting to think that it might be simpler to just use both, if possible.

**Comment by lecardozo** [comment]
You can try to import only the functions you use for each one of those pkgs instead of import the whole pkg to namespace.
About using both packages, I think it's better to keep just one of them. Since those pkgs share a lot of functionality, I believe almost everything you do with one of them could be done with the other as well.
In favor of keeping things clear I vote for using igraph OR network, not both.

**Comment by pedrostrusso** [comment]
I completely agree, but given the urgency that we want to publish the package, I'll focus on making this separation at a later update, when we try to improve the code. 
As for the imports issues, your suggestion worked for the first and third warnings. Any thoughts on what we should do about WGCNA's `cor` function?

**Comment by lecardozo** [comment]
Alright then! :smiley: 
The `WGCNA::cor` vs. `stats::cor` issue will probably be solved by choosing only one of them to use in the whole pkg.
