### ISSUE TITLE
counts and logcounts as input produces different results

### ISSUE THREAD

**Issue by Cumol** [csbl-usp/CEMiTool#32]
When using RNA-Seq data, in which form should the data be?

I ran the pipeline once using the normalized counts generated by DESeq2 and another time with the log transformed version.

I got completely different results. What is happening here? And why is it happening?

**Comment by pedrostrusso** [comment]
Hi @Cumol thanks for using CEMiTool. 

Yes, it's not surprising that you got different results, since CEMiTool by default uses Pearson correlation, which looks for linearly dependent variables. When you log transform them, you change the relationships between genes, ceasing to be linear. If you want a correlation method that is robust to these types of transformation, you can use Spearman's rho. You can change the correlation type using the `cor_method` parameter on your funciton call, as follows:

`cem <- cemitool(expr, cor_method="spearman")`

Please note that this considerably increases computational time.

**Comment by Cumol** [comment]
Thank you for the swift response @pedrostrusso 

Would you then suggest to leave the counts as-is? I only log-transformed them as I saw the input data used (in the example) to be log-transformed.

**Comment by pedrostrusso** [comment]
I think that there isn't a clear-cut response for this, since it depends a lot on your data, its distributions and what you're trying to show. You could try to see which of them provides better results for your analysis and stick to that method. Also, item 4 of the [WGCNA faq](https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/faq.html) may provide further guidance.

**Comment by Cumol** [comment]
I am trying to use data that was batch-corrected with limma's removeBatchEffect function that expects log-transformed data.

I just tried to use cor_method="spearman" and got an error with the log-transformed data, need to run the dignostic on the data.
