### ISSUE TITLE
Exporting a gene network 

### ISSUE THREAD

**Issue by castvox** [csbl-usp/CEMiTool#44]
Hello!

I understand cemitool can use an external PPI network to visualize gene interactions but I was wondering if I am able to visualize the network by itself, **without** using an external gene interaction file? In WGCNA you can calculate the topological overlap matrix and visualize the gene intramodular connectivity by exporting to cytoscape. So I was curious if cemitool has this feature too. 

Thank you

**Comment by pedrostrusso** [comment]
Hi @castvox, 

We decided against implementing this feature because we saw that genes in a module usually have such high correlations amongst themselves (most above 0.9) that the resulting network graphs would only be hairballs, not conveying useful information. 

That said, you could export module data to Cytoscape using the following:

library(CEMiTool)
data(cem)

# Example using module M4
m4genes <- module_genes(cem, "M4")["genes"]
m4adj <- adj_data(cem)[m4genes, m4genes]

#To put the data in edge list format for Cytoscape, you can melt it using reshape2:
res <- reshape2::melt(m4adj)

**Comment by castvox** [comment]
Hello @pedrostrusso,

Thank you so much for this code but when I tried to extract M4 genes I got this error:

`Error in adj_data(cem)[m4genes, m4genes] : invalid subscript type 'list'`

**Comment by castvox** [comment]
Hello @pedrostrusso 

I believe I solved this problem by 

`m4genes <- module_genes(cem, "M4")["genes"]`
`m4genes<-unlist(m4genes)`
`m4adj <- adj_data(cem)[m4genes, m4genes]`
`res <- reshape2::melt(m4adj)`

Thank you again!

**Comment by pedrostrusso** [comment]
I actually meant to write `m4genes <- module_genes(cem, "M4")[, "genes"]`, which would avoid needing to use `unlist`, but anyway I'm glad you were able to work it out. I'll close the issue for now.
