### ISSUE TITLE
Number of selected genes

### ISSUE THREAD

**Issue by javijevi** [csbl-usp/CEMiTool#47]
When using 'cemitool' function with 'filter=TRUE' and different 'filter_pval' values, I obtain always the same number of genes in the file 'Tables/module.tsv' (the same obtained when using the default 'filter_pval=0.1') even getting different numbers of 'Selected data: XXXX genes selected' in the 'cem' object returned.

My code is:
> library("CEMiTool")
> df <- read.csv('all.htseq-count.tsv.rpkms.tsv', header=TRUE, row.names=1, sep='\t')
> cem <- cemitool(df, apply_vst=TRUE, filter=TRUE, set_beta=16, verbose=TRUE, filter_pval=0.2)
> cem
CEMiTool Object
- Number of modules: 13 
- Modules (data.frame: 2122x2): 
                 genes modules
1 Mapoly0011s0071.v3.1      M3
2 Mapoly0068s0071.v3.1      M3
3 Mapoly0023s0166.v3.1      M2
- Expression file: data.frame with 19287 genes and 44 samples
- Selected data: 3521 genes selected
- Gene Set Enrichment Analysis: null
- Over Representation Analysis: null
- Profile plot: ok
- Enrichment plot: null
- ORA barplot: null
- Beta x R2 plot: null
- Mean connectivity plot: null
> write_files(cem, force=TRUE)

Am I missing something?

Thanks in advance, and congratulations for the tool,

Javier.

**Comment by pedrostrusso** [comment]
Hi Javier, thanks for using CEMiTool!

This is a known issue in the package, which should be fixed with the next update I plan to release in a few days. In the meantime, please try using the development version (which can be installed using `devtools::install_github("csbl-usp/CEMiTool"`). Please let me know if you find additional problems. 

Best, 
Pedro

**Comment by javijevi** [comment]
Great! It solved the issue, so I close it. Thanks again.
