### ISSUE TITLE
Could not specify the parameter Beta. No modules found.

### ISSUE THREAD

**Issue by bjstewart1** [csbl-usp/CEMiTool#60]
This error
`Could not specify the parameter Beta. No modules found.`
Comes up very often on numerous datasets.
Can you offer any advice for analysis/preprocessing that will help?

**Comment by pedrostrusso** [comment]
Hi @bjstewart1 yes, as you said this is quite a common situation many users encounter when using CEMiTool simply because it (and WGCNA) are based on the scale-free model, which although widespread, is not ubiquitous. That said, there are a few things you can do to help. 

1. Check if your data contain at least 20 samples, which we consider to be the very least for any meaningful analysis. 
2. Make sure your data were normalized adequately prior to running CEMiTool. Normalization techniques which have been used successfully in the past include RPKM, FPKM, TMM, quantile...
3. You can see if your data have too much dependence between the mean and variance. If this is the case, using the `apply_vst = TRUE` parameter can help.
4. Another possibility is that CEMiTool was too stringent in the beta selection step of analysis. You can check this by using `plot_beta_r2(cem)`, and then `show_plot(cem, "beta_r2")`. You can then manually select a beta value with the `set_beta` value. 
5. Finally, you can make CEMiTool select a beta value based on the number of samples you have with the `force_beta` parameter.
Please see the [WGCNA FAQ](https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/faq.html) for more info and caveats on the last point, specifically item 6.

**Comment by bjstewart1** [comment]
Thanks. Useful reply.
