### ISSUE TITLE
Errors when expression matrix has NAs

### ISSUE THREAD

**Issue by allakarpova** [csbl-usp/CEMiTool#72]
Hi! I've been running into this error coming from `pracma::gammainc(bh/x, ah)['uppinc']` implementation within `select_genes()` function:

` Error in if (a < 0) stop("Argument 'a' must be real and nonnegative.") : 
  missing value where TRUE/FALSE needed ` 

I ran Cemitool over a month ago, and it wasn't a problem back then. My data table contains missing values, so I think this might cause troubles when `ah` and `bh` are calculated. So maybe adding na.rm = T to this line in `select_genes()` will solve this issue:

`expr_var <- matrixStats::rowVars(expr, na.rm=TRUE)`

Could you comment on this please.
Thanks!

**Comment by pedrostrusso** [comment]
Hi @allakarpova, first I'm a bit more interested as to why you have NA values in your dataset. Note that CEMiTool was created with a very narrow focus in mind, that is, for analyzing RNAseq and microarray data, both of which usually don't have NA values in them. Although the fix you suggest would indeed be simple to implement, it doesn't guarantee that there won't be any further problem down the pipeline. So unless you can provide a compelling argument otherwise, I can't justify altering the code (and giving myself the subsequent testing, revision, etc hassle) to accomodate for your specific corner case. I kindly ask for your understanding, and thanks for using CEMiTool.

**Comment by allakarpova** [comment]
Hi Pedro,
I'm using protein mass-spec measurements, which are essentially log-ratios of intensities in a testing sample vs pooled sample. Then log ratios for each sample are normalized by subtracting the median from all values. Could you please tell me if it okay to apply CEMiTool on such data ? I'm attaching the histogram, QQ and mean-variance plots if it helps.
Thanks,
Alla
[hist.pdf](https://github.com/csbl-usp/CEMiTool/files/6223541/hist.pdf)
[qq.pdf](https://github.com/csbl-usp/CEMiTool/files/6223537/qq.pdf)
[mean_var.pdf](https://github.com/csbl-usp/CEMiTool/files/6223538/mean_var.pdf)

**Comment by pedrostrusso** [comment]
Hi Alla, 
Well, it depends on what you think is okay. From a technical standpoint, if you can find a way to deal with your NA values (say, replacing them with 0 or something), it should run fine. As for if the analysis will make sense, that's a different story. Can you be sure that your data follow the scale-free topology distribution assumed by the WGCNA method? Even if they do, does it make sense to represent your data as a network, since they are ratios and not "actual values"? I don't think that these are easy questions to answer, so I'd suggest you first familiarize yourself with the method and then see if it makes sense to use for your data.
