### ISSUE TITLE
Issue with specifying parameter beta

### ISSUE THREAD

**Issue by ashaypatel** [csbl-usp/CEMiTool#74]
When I run cemitool() it says:
`Could not specify the parameter Beta. No modules found.`
`Unable to find parameter beta. Please check diagnostic plots with function diagnostic_report().`

I get cemitool() to run successfully when I:
`force_beta=TRUE`

Is this appropriate?
My beta r2 plot is below. 

![beta_r2_plot](https://user-images.githubusercontent.com/81838264/114121735-c1983100-98a3-11eb-858d-0911d01491b6.jpeg)

Thanks!

**Comment by pedrostrusso** [comment]
Hi @ashaypatel, the `force_beta` argument will select a beta value based on the suggestion outlined in item 6 of the [WGCNA FAQ](https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/faq.html), so please be aware of the potential caveats of using this argument. 
Your automatic beta selection failed because CEMiTool was unable to find a range of beta values with R² values above 0.8. As I'm sure you're aware, higher R² values imply in higher adherence to the scale-free model, but higher beta values will result in lower network connectivity, so you have to decide how much of the trade-off you're willing to accept. Hope this helps.

**Comment by ashaypatel** [comment]
Thank you. Is there a way to set max module size for detection? I see min_ngen, but I don't see a max version of this parameter in the [manual](https://www.bioconductor.org/packages/release/bioc/manuals/CEMiTool/man/CEMiTool.pdf)

**Comment by pedrostrusso** [comment]
Hi @ashaypatel that functionality is currently not implemented in CEMiTool.
