### ISSUE TITLE
cemitool() fails if input is tibble

### ISSUE THREAD

**Issue by BaxW** [csbl-usp/CEMiTool#80]
Thanks for your hard work on this awesome package. I've found a small issue:
When the expression data is a tibble, cemitool() fails to calculate new MEs, returning an error message: "stats should be named"
(looks like it's specifically a call to fgsea::fgsea() that fails)

Maybe I'm just missing something, but here's the code to reproduce this:

```
data(expr0)
data(sample_annot)

cem <- cemitool(expr0, sample_annot) # works
exprTib <- tibble::as_tibble(expr0)
cem <- cemitool(exprTib, sample_annot)  # fails
```
converting back to a true data.frame doesn't fix it 

```
expr <- as.data.frame(exprTib)
cem <- cemitool(expr, sample_annot) # still fails 
```
[sessionInfo](https://github.com/csbl-usp/CEMiTool/files/6759106/sessionInfo.txt)

**Comment by pedrostrusso** [comment]
Hi @BaxW thanks for your message. I see you're using CEMiTool version 1.10.2, I tried running your code on CEMiTool version 1.14.0 and it worked, I just got some (possibly unrelated) warnings. On the other hand, I wouldn't recommend you run CEMiTool with tibbles since they remove rownames from your dataframe. That's probably why it stops working when you try to convert back to regular data.frames, your tibble loses the rownames. It will probably also mess up any analyses in which the gene names are actually used, like ORA and creating interaction plots.
