### ISSUE TITLE
Difference between profile plot and GSEA

### ISSUE THREAD

**Issue by pedrostrusso** [csbl-usp/CEMiTool#91]
Hi Pedro, 

I believe I have one last question for you, I do feel bad for taking up your time but I want to ensure my thinking is correct before I use these data in publication. Take for example the profile plot for M2:
![image](https://user-images.githubusercontent.com/60767620/154206415-d995f2cc-cf92-4095-8cfe-ce9fa77534e8.png)
If most the genes in this module tend to be overexpressed in the 3D CTRL group, why is it that for the GSEA the NES scores are only positive for 2D MPP? and negative for the remaining groups? In other words, why isn't the 3D CTRL group's NES score sticking out, like the profile plot would suggest it would? 
![image](https://user-images.githubusercontent.com/60767620/154206587-a9a1dcbf-f829-4c8c-856b-f16b641df021.png)

_Originally posted by @NickFiore-1 in https://github.com/csbl-usp/CEMiTool/issues/90#issuecomment-1041144839_

**Comment by pedrostrusso** [comment]
Is this the same data you sent me previously? I can't seem to find the expression data of the 2D groups in any of the files you sent me.

**Comment by NickFiore-1** [comment]
No this is a new analysis. Just sent over the files you will need to replicate these results.

Best
Nick

**Comment by NickFiore-1** [comment]
Hi Pedro, 

After studying this problem long enough, I realized that (for a still unknown reason) the class names above the GSEA NES plots were immovable (i.e. would not reposition, even if I changed my input phenotype and expression files). So as a 'hard' fix I moved my columns around to 'fit' the class names above the GSEA plot, now the profile plots' match the NESs in the GSEA plot and the GSEA enrichment results are making a lot more sense (e.g., agreeing with previous data from ORA & IPA pathway enrichments)
![image](https://user-images.githubusercontent.com/60767620/155242210-dbaa2c59-114b-4f8d-a410-01784760848e.png)

I'll close the issue since I know you are super busy! Might be good to figure out if it's an issue on my end or if something else at some point in the future.

Thanks for everything.

Best,
Nick
