### ISSUE TITLE
Error in .local(cem, ...) :    Sample annotation file does not contain all samples in expression file. Please input new sample annotation file using function sample_annotation()

### ISSUE THREAD

**Issue by jacraft** [csbl-usp/CEMiTool#93]
I am getting the same error message as found by others concerning the samples in the expression file and those in the annotation file and I cannot identify where the error is. I have checked the format of both files compared to the expr(0) and sample_annot files in the tutorial (www.bioconductor.org/packages/devel/bioc/vignettes/CEMiTool/inst/doc/CEMiTool.html) and see no differences. 
My input expression file was salmon_uniprot_TMM.csv from which I deleted duplicate entries and set "uniprot" as rownames to generate test_df2

#input data
sal_uniprot_TMM_cemitool<-read.csv(here("salmon_uniprot_TMM.csv"))
#delete duplicate rows based on uniprot
test_df <- sal_uniprot_TMM_cemitool %>%
  arrange(uniprot) %>%
  filter(duplicated(uniprot) == FALSE)
#specify uniprot as rownames
test_df2 <- column_to_rownames(test_df, var="uniprot")

I then ran 
cem<-cemitool(test_df2, sample_annot) and get
cem gave
CEMiTool Object
- Number of modules: 5 etc

I then ran
sample_annotation(cem, 
                  sample_name_column="SampleName", 
                  class_column="Class") <- sample_annot
followed by 
cem <- mod_gsea(cem)
cem <- plot_gsea(cem)
show_plot(cem, "gsea")

and get
Error in .local(cem, ...) : 
  Sample annotation file does not contain all samples in expression file. Please input new sample annotation file using function sample_annotation()
> cem <- plot_gsea(cem)
Error in .local(cem, ...) : No GSEA data! Did you run mod_gsea()?
> show_plot(cem, "gsea")
list()
I have run 
generate_report(cem) 
which provides Module data but no Profile Plot
I have also run
diagnostic_report(cem) but it contains none of the expected files.
I would be most grateful if you could discover where I am going wrong.
[sample_annot.csv](https://github.com/csbl-usp/CEMiTool/files/9505575/sample_annot.csv)
[salmon_uniprot_TMM.csv](https://github.com/csbl-usp/CEMiTool/files/9505576/salmon_uniprot_TMM.csv)

**Comment by pedrostrusso** [comment]
Ok, thanks John, just to know if we were running the same thing. Now, that error from WGCNA happens because CEMiTool's automatic filtering is a bit too stringent at times (for your data, only 1 gene remained lol) so if you set `filter = FALSE` in your `cemitool()` call things should be ok from there. 
That said, when I ran your data with `filter = FALSE`, CEMiTool failed to automatically find a reasonable beta value. However, after running the diagnostics plots - and I don't want to bias you too much -  but it seems that a beta value of at least 10 would be ideal for your analysis (see below). You can then set this value in your `cemitool()` call using the `set_beta` parameter to 10 (or higher) and then proceed with your interpretation of the results. 

![image](https://user-images.githubusercontent.com/10830114/189173911-4247d353-f9c9-4ed6-81ed-705fbfda5723.png)

**Comment by jacraft** [comment]
Thanks Pedro
That is much appreciated.
I am currently running cem<-cemitool(test_df2, sample_annot, filter = FALSE, set_beta=10)
and it produced the usual stats tables followed by
..connectivity..
..matrix multiplication (system BLAS)..
but now appears to have stalled. It has been like that for an hour which did not happen with the tutorial data. I do not know if it has stalled or indeed takes a long time.
Best wishes
John
________________________________

**Comment by pedrostrusso** [comment]
Hi John, it probably will take a while since now without the filter the function has a lot more genes to deal with and as you can see it has to perform some matrix multiplications, which are quite memory intensive. You mentioned you're running on an HPC so I don't think you should run into memory issues though. One thing you could do is also set the `verbose=TRUE` parameter to the `cemitool()` call, which will provide more output as to what the code is doing. Anyway, the original problem seems to be resolved so I'll close the issue for now but feel free to open another one if you still have trouble.

**Comment by jacraft** [comment]
Yep you were right it has now completed. Took a quick look but too late to do any more tonight
Many thanks for your help.
John
________________________________
